name: Samsung EROFS to EXT4
on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:
    inputs:
      GSI:
        description: 'Samfw Link For AP'
        required: true
        default: 'test'
      
      Firmware:
        description: 'Firmware version'
        required: true
        default: 'A055FXXU2AWK1'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y cpio bc simg2img lz4 git device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full android-sdk-libsparse-utils erofs-utils
        sudo apt install -y zip xz-utils unzip p7zip-full wget
        
    - name: Preparing Files
      run: |
        # Downloading and extracting necessary files
        wget https://sourceforge.net/projects/samsung-galaxy-a01-m01/files/erofs.zip
        unzip erofs.zip
        rm -r erofs.zip

    - name: Downloading your GSI
      run: |
        # Downloading GSI
        wget -O ap.zip ${{ github.event.inputs.GSI }} 
        chmod +x *
        chmod 755 bin/*
        chmod 755 aik/bin/*

    - name: Converting
      run: |
        # Building the ROM
        ./down

    - name: Rename file
      run: mv ./out/EXT4_RW_AP.zip ./out/${{ github.event.inputs.Firmware }}.zip

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./out/${{ github.event.inputs.Firmware }}.zip
        asset_name: ${{ github.event.inputs.Firmware }}.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
